language: python
python:
  - 2.7
  - 3.4
  - 3.5
  - pypy

cache:
  apt: true
  pip: true
  directories:
    - $HOME/download-cache

before_install:
  - mkdir -p $HOME/download-cache
  - sudo apt-get update
  - sudo apt-get install default-jdk

install:
  - pip install coveralls
  - pip install tox
  - pip install -e .

after_success:
  coveralls

script:
  - tox -e $TOX_ENV

env:
  global:
    - PIP_DOWNLOAD_CACHE="pip_download_cache"
  matrix:
    - DJANGO_VERSION=">=1.8,<1.9"
    - DJANGO_VERSION=">=1.9,<1.10"
    - DJANGO_VERSION="==1.10a1"

matrix:
  allow_failures:
    - env: DJANGO_VERSION="==1.10a1"

services:
  - elasticsearch

notifications:
  email: false
