language: python
python: "2.7"

cache:
  directories:
    - pip_download_cache

before_install:
  - mkdir -p $PIP_DOWNLOAD_CACHE
  - sudo apt-get update
  - sudo apt-get install default-jdk

install:
  - pip install coveralls
  - pip install tox
  - pip install -e .

after_success:
  coveralls

script:
  - tox -e $TOX_ENV

env:
  global:
    - PIP_DOWNLOAD_CACHE="pip_download_cache"
  matrix:
    - TOX_ENV=docs
    - TOX_ENV=py27-django1.8
    - TOX_ENV=py34-django1.8
    - TOX_ENV=py35-django1.8
    - TOX_ENV=py27-django1.9
    - TOX_ENV=py34-django1.9
    - TOX_ENV=py35-django1.9

services:
  - elasticsearch

notifications:
  email: false
